syntax on

colorscheme dim

set number
set nowrap
set smartcase
set cursorline
set smartindent expandtab shiftwidth=2 softtabstop=2
set backspace=indent,eol,start
set noswapfile nobackup
set colorcolumn=81
set incsearch hlsearch
set list listchars=eol:¬,tab:>·,trail:~,extends:>,precedes:<,space:·
set belloff=all
set undofile undodir=~/.vim/undodir
set scrolloff=999

set rtp+=/usr/local/opt/fzf
nnoremap <silent> <C-p> :FZF<CR>

let g:netrw_liststyle = 3

let g:ale_fix_on_save = 1
let g:ale_linters = {'javascript': ['eslint'], 'json': ['eslint']}
let g:ale_fixers = {'javascript': ['prettier'], 'json': ['prettier']}

let g:airline#extensions#ale#enabled = 1

let g:markdown_enable_spell_checking = 0

call plug#begin('~/.vim/plugged')
Plug 'airblade/vim-gitgutter'
Plug 'dense-analysis/ale'
Plug 'gabrielelana/vim-markdown'
Plug 'jonsmithers/vim-html-template-literals'
Plug 'jremmen/vim-ripgrep'
Plug 'pangloss/vim-javascript'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-vinegar'
Plug 'vim-airline/vim-airline'
call plug#end()
